<h1><?php $this->out($this->title) ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper('UsersMenuHelper')->show(); ?>
</div>

<div>
    <?php echo $this->_viewHelperBroker->getHelper(
        'FormHelper',
        array('action'      => '/users/addDo/',
              'id'          => 'fr1',
              'method'      => 'post',
              'buttonValue' => 'New User',
              'controls'    => array(
                  array(
                      'field'   => 'usuario',
                      'type'    => 'text',
                  ),
                  array(
                      'field'   => 'password',
                      'type'    => 'password',
                  )
              )
        ))->show(); ?>
</div>
