<div class="page-header">
    <h1><?php $this->out($this->title);?></h1> 
    <h1><small><?php $this->out($this->dates[0]->format('d/m/Y') . ' | ' 
            . $this->dates[1]->format('d/m/Y')) ?></small></h1>
</div>
<?php echo $this->_viewHelperBroker->getHelper('UsersMenuHelper')->show(); ?>
<div>
    <table class="table table-hover">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Riesgo</th>
            <th>Facturado</th>
            <th>Proporcion</th>
        </tr>
    <?php foreach ($this->clientes as $cliente): ?>
        <tr>
            <td><?php $this->out($cliente['ID']); ?></td>
            <td><?php echo utf8_encode($cliente['Nombre']); ?></td>
            <td><?php $this->out(number_format($cliente['Riesgo'], 2, ',', '.')); ?></td>
            <td><?php $this->out(number_format($cliente['Facturado'], 2, ',', '.')); ?></td>
            <td><?php $this->out($cliente['Proporcion']); ?></td>
        </tr>
    <?php endforeach; ?>
    </table>
        <button type="button" id="gencsv" class="btn btn-primary">Descargar como CSV</button>
</div>