<h1><?php echo $this->title ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper(
        'FormHelper',
        array('action'      => '/users/getExpirationControlDo/',
              'id'          => 'fr1',
              'method'      => 'get',
              'buttonValue' => 'Enviar',
              'controls'    => array(
                  array(
                      'field'   => 'fecha_inicial',
                      'type'    => 'date',
                      'value'   => $this->dates[0]->format('Y-m-d'),
                  ),
                  array(
                      'field'   => 'fecha_final',
                      'type'    => 'date',
                      'value'   => $this->dates[1]->format('Y-m-d'),
                  ),
                  array(
                      'field'   => 'filtro_dias',
                      'type'    => 'number',
                      'value'   => 30,
                  )
              )
        ))->show(); ?>
</div>
