<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/js/jquery-1.10.2.min.js"></script>
<script src="/js/printTable.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<!-- Latest compiled and minified JavaScript -->
<script src="/js/bootstrap.min.js"></script>
<!--<script src="http://getbootstrap.com/docs-assets/js/holder.js"></script>-->
</body>
</html>